# -----------------------------
# HC Help
# by Global Emergency Response
#    a division of CRI
# -----------------------------

trigger:
- develop
- main

pool:
  name: Hosted VS2017

jobs:
- job: A
  displayName: 'HC Help Dev'
  continueOnError: true
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
  steps:
  - task: S3Upload@1
    inputs:
      awsCredentials: 'geraws-azure'
      regionName: 'us-east-1'
      bucketName: 'ger-help'
      sourceFolder: '$(System.DefaultWorkingDirectory)'
      globExpressions: '**'
      targetFolder: 'develop'
      createBucket: true

- job: B
  displayName: 'HC Help Main'
  continueOnError: true
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  steps:
  - task: S3Upload@1
    inputs:
      awsCredentials: 'geraws-azure'
      regionName: 'us-east-1'
      bucketName: 'ger-help'
      sourceFolder: '$(System.DefaultWorkingDirectory)'
      globExpressions: '**'
      targetFolder: 'Main'
      createBucket: true