# -----------------------------
# HC Help
# by Global Emergency Response
#    a division of CRI
# -----------------------------

trigger:
- develop
- main

pool:
  name: Hosted VS2017

steps:

- task: PowerShell@2
  displayName: 'Copy Changed Files'
  inputs:
    targetType: 'inline'
    script:
      $targetfolder = "$(Build.StagingDirectory)" + "/"

      function CopyFiles{
        param( [string]$source)
        $target = $targetfolder + $source
        New-Item -Force $target
        copy-item $source $target -Force
      }

      $changes = git diff --name-only --relative --diff-filter AMR HEAD^ HEAD .
      
      if($changes -is [string]){CopyFiles $changes}
      else
      {
           if($changes -is [array])
           {
                 foreach($change in $changes){CopyFiles $change}
           }
      }

- task: S3Upload@1
  inputs:
    awsCredentials: 'geraws-azure'
    regionName: 'us-east-1'
    bucketName: 'ger-help'
    sourceFolder: '$(System.ArtifactStagingDirectory)'
    globExpressions: '**'
    targetFolder: '$(Build.SourceBranchName)'
    createBucket: true